import { request } from 'umi';
import { heroList, toolList, skillList } from '@/api/index';

export function getHeroList() {
  // return request(heroList);
  return [
    {
      ename: 105,
      cname: '廉颇',
      title: '正义爆轰',
      new_type: 0,
      hero_type: 3,
      skin_name: '正义爆轰|地狱岩魂',
    },
    {
      ename: 106,
      cname: '小乔',
      title: '恋之微风',
      new_type: 0,
      hero_type: 2,
      skin_name: '恋之微风|万圣前夜|天鹅之梦|纯白花嫁|缤纷独角兽',
    },
    {
      ename: 107,
      cname: '赵云',
      title: '苍天翔龙',
      new_type: 0,
      hero_type: 1,
      hero_type2: 4,
      skin_name: '苍天翔龙|忍●炎影|未来纪元|皇家上将|嘻哈天王|白执事|引擎之心',
    },
    {
      ename: 108,
      cname: '墨子',
      title: '和平守望',
      new_type: 0,
      hero_type: 2,
      hero_type2: 1,
      skin_name: '和平守望|金属风暴|龙骑士|进击墨子号',
    },
    {
      ename: 109,
      cname: '妲己',
      title: '魅力之狐',
      pay_type: 11,
      new_type: 0,
      hero_type: 2,
      skin_name: '魅惑之狐|女仆咖啡|魅力维加斯|仙境爱丽丝|少女阿狸|热情桑巴',
    },
    {
      ename: 110,
      cname: '嬴政',
      title: '王者独尊',
      new_type: 0,
      hero_type: 2,
      skin_name: '王者独尊|摇滚巨星|暗夜贵公子|优雅恋人|白昼王子',
    },
    {
      ename: 111,
      cname: '孙尚香',
      title: '千金重弩',
      new_type: 0,
      hero_type: 5,
      skin_name:
        '千金重弩|火炮千金|水果甜心|蔷薇恋人|杀手不太冷|末日机甲|沉稳之力',
    },
    {
      ename: 112,
      cname: '鲁班七号',
      title: '机关造物',
      new_type: 0,
      hero_type: 5,
      skin_name: '机关造物|木偶奇遇记|福禄兄弟|电玩小子|星空梦想',
    },
    {
      ename: 113,
      cname: '庄周',
      title: '逍遥梦幻',
      new_type: 0,
      hero_type: 6,
      hero_type2: 3,
      skin_name: '逍遥幻梦|鲤鱼之梦|蜃楼王|云端筑梦师',
    },
    {
      ename: 114,
      cname: '刘禅',
      title: '暴走机关',
      new_type: 0,
      hero_type: 6,
      hero_type2: 3,
      skin_name: '暴走机关|英喵野望|绅士熊喵|天才门将',
    },
    {
      ename: 115,
      cname: '高渐离',
      title: '叛逆吟游',
      new_type: 0,
      hero_type: 2,
      skin_name: '叛逆吟游|金属狂潮|死亡摇滚',
    },
    {
      ename: 116,
      cname: '阿轲',
      title: '信念之刃',
      new_type: 0,
      hero_type: 4,
      skin_name: '信念之刃|爱心护理|暗夜猫娘|致命风华|节奏热浪',
    },
    {
      ename: 117,
      cname: '钟无艳',
      title: '野蛮之锤',
      new_type: 0,
      hero_type: 1,
      hero_type2: 3,
      skin_name: '野蛮之锤|生化警戒|王者之锤|海滩丽影',
    },
    {
      ename: 118,
      cname: '孙膑',
      title: '逆流之时',
      new_type: 0,
      hero_type: 6,
      hero_type2: 2,
      skin_name: '逆流之时|未来旅行|天使之翼|妖精王',
    },
    {
      ename: 119,
      cname: '扁鹊',
      title: '善恶怪医',
      new_type: 0,
      hero_type: 2,
      skin_name: '善恶怪医|救世之瞳|化身博士|炼金王',
    },
    {
      ename: 120,
      cname: '白起',
      title: '最终兵器',
      new_type: 0,
      hero_type: 3,
      skin_name: '最终兵器|白色死神|狰|星夜王子',
    },
    {
      ename: 121,
      cname: '芈月',
      title: '永恒之月',
      new_type: 0,
      hero_type: 2,
      hero_type2: 3,
      skin_name: '永恒之月|红桃皇后|大秦宣太后|重明',
    },
    {
      ename: 123,
      cname: '吕布',
      title: '无双之魔',
      new_type: 0,
      hero_type: 1,
      hero_type2: 3,
      skin_name: '无双之魔|圣诞狂欢|天魔缭乱|末日机甲|猎兽之王',
    },
    {
      ename: 124,
      cname: '周瑜',
      title: '铁血都督',
      new_type: 0,
      hero_type: 2,
      skin_name: '铁血都督|海军大将|真爱至上',
    },
    {
      ename: 126,
      cname: '夏侯惇',
      title: '不羁之风',
      pay_type: 10,
      new_type: 0,
      hero_type: 3,
      hero_type2: 1,
      skin_name: '不羁之风|战争骑士|乘风破浪|无限飓风号',
    },
    {
      ename: 127,
      cname: '甄姬',
      title: '洛神降临',
      pay_type: 10,
      new_type: 0,
      hero_type: 2,
      skin_name: '洛神降临|冰雪圆舞曲|花好人间|游园惊梦',
    },
    {
      ename: 128,
      cname: '曹操',
      title: '鲜血枭雄',
      new_type: 0,
      hero_type: 1,
      skin_name: '鲜血枭雄|超能战警|幽灵船长|死神来了|烛龙',
    },
    {
      ename: 129,
      cname: '典韦',
      title: '狂战士',
      new_type: 0,
      hero_type: 1,
      skin_name: '狂战士|黄金武士|穷奇',
    },
    {
      ename: 130,
      cname: '宫本武藏',
      title: '剑圣',
      new_type: 0,
      hero_type: 1,
      skin_name: '剑圣|鬼剑武藏|未来纪元|万象初新|地狱之眼|霸王丸',
    },
    {
      ename: 131,
      cname: '李白',
      title: '青莲剑仙',
      new_type: 0,
      hero_type: 4,
      skin_name: '青莲剑仙|范海辛|千年之狐|凤求凰|敏锐之力',
    },
    {
      ename: 132,
      cname: '马可波罗',
      title: '远游之枪',
      new_type: 0,
      hero_type: 5,
      skin_name: '远游之枪|激情绿茵|逐梦之星',
    },
    {
      ename: 133,
      cname: '狄仁杰',
      title: '断案大师',
      pay_type: 11,
      new_type: 0,
      hero_type: 5,
      skin_name: '断案大师|锦衣卫|魔术师|超时空战士|阴阳师',
    },
    {
      ename: 134,
      cname: '达摩',
      title: '拳僧',
      new_type: 0,
      hero_type: 1,
      hero_type2: 3,
      skin_name: '拳僧|大发明家|拳王',
    },
    {
      ename: 135,
      cname: '项羽',
      title: '霸王',
      new_type: 0,
      hero_type: 3,
      skin_name: '霸王|帝国元帅|苍穹之光|海滩派对|职棒王牌|霸王别姬|科学大爆炸',
    },
    {
      ename: 136,
      cname: '武则天',
      title: '女帝',
      new_type: 0,
      hero_type: 2,
      skin_name: '女帝|东方不败|海洋之心',
    },
    {
      ename: 139,
      cname: '老夫子',
      title: '万古长明',
      new_type: 0,
      hero_type: 1,
      skin_name: '万古长明|潮流仙人|圣诞老人|功夫老勺',
    },
    {
      ename: 140,
      cname: '关羽',
      title: '一骑当千',
      new_type: 0,
      hero_type: 1,
      skin_name: '一骑当千|天启骑士|冰锋战神|龙腾万里',
    },
    {
      ename: 141,
      cname: '貂蝉',
      title: '绝世舞姬',
      new_type: 0,
      hero_type: 2,
      hero_type2: 4,
      skin_name: '绝世舞姬|异域舞娘|圣诞恋歌|逐梦之音|仲夏夜之梦',
    },
    {
      ename: 142,
      cname: '安琪拉',
      title: '暗夜萝莉',
      new_type: 0,
      hero_type: 2,
      skin_name: '暗夜萝莉|玩偶对对碰|魔法小厨娘|心灵骇客|如懿',
    },
    {
      ename: 144,
      cname: '程咬金',
      title: '热烈之斧',
      new_type: 0,
      hero_type: 3,
      hero_type2: 1,
      skin_name: '热烈之斧|爱与正义|星际陆战队|华尔街大亨|功夫厨神',
    },
    {
      ename: 146,
      cname: '露娜',
      title: '月光之女',
      pay_type: 10,
      new_type: 0,
      hero_type: 1,
      hero_type2: 2,
      skin_name: '月光之女|哥特玫瑰|绯红之刃|紫霞仙子|一生所爱',
    },
    {
      ename: 148,
      cname: '姜子牙',
      title: '太古魔导',
      pay_type: 10,
      new_type: 0,
      hero_type: 2,
      hero_type2: 6,
      skin_name: '太古魔导|时尚教父',
    },
    {
      ename: 149,
      cname: '刘邦',
      title: '双面君主',
      new_type: 0,
      hero_type: 3,
      skin_name: '双面君主|圣殿之光|德古拉伯爵',
    },
    {
      ename: 150,
      cname: '韩信',
      title: '国士无双',
      new_type: 0,
      hero_type: 4,
      skin_name: '国士无双|街头霸王|教廷特使|白龙吟|逐梦之影',
    },
    {
      ename: 152,
      cname: '王昭君',
      title: '冰雪之华',
      new_type: 0,
      hero_type: 2,
      skin_name: '冰雪之华|精灵公主|偶像歌手|凤凰于飞|幻想奇妙夜',
    },
    {
      ename: 153,
      cname: '兰陵王',
      title: '暗影刀锋',
      new_type: 0,
      hero_type: 4,
      skin_name: '暗影刀锋|隐刃|暗隐猎兽者',
    },
    {
      ename: 154,
      cname: '花木兰',
      title: '传说之刃',
      new_type: 0,
      hero_type: 1,
      hero_type2: 4,
      skin_name: '传说之刃|剑舞者|兔女郎|水晶猎龙者|青春决赛季|冠军飞将|瑞麟志',
    },
    {
      ename: 156,
      cname: '张良',
      title: '言灵之书',
      new_type: 0,
      hero_type: 2,
      skin_name: '言灵之书|天堂福音|一千零一夜|幽兰居士',
    },
    {
      ename: 157,
      cname: '不知火舞',
      title: '明媚烈焰',
      new_type: 0,
      hero_type: 2,
      hero_type2: 4,
      skin_name: '明媚烈焰',
    },
    {
      ename: 162,
      cname: '娜可露露',
      title: '鹰之守护',
      new_type: 0,
      hero_type: 4,
      skin_name: '鹰之守护',
    },
    {
      ename: 163,
      cname: '橘右京',
      title: '神梦一刀',
      new_type: 0,
      hero_type: 4,
      hero_type2: 1,
      skin_name: '神梦一刀',
    },
    {
      ename: 166,
      cname: '亚瑟',
      title: '圣骑之力',
      pay_type: 11,
      new_type: 0,
      hero_type: 1,
      hero_type2: 3,
      skin_name: '圣骑之力|死亡骑士|狮心王|心灵战警',
    },
    {
      ename: 167,
      cname: '孙悟空',
      title: '齐天大圣',
      new_type: 0,
      hero_type: 4,
      hero_type2: 1,
      skin_name: '齐天大圣|地狱火|西部大镖客|美猴王|至尊宝|全息碎影|大圣娶亲',
    },
    {
      ename: 168,
      cname: '牛魔',
      title: '精英酋长',
      new_type: 0,
      hero_type: 3,
      hero_type2: 6,
      skin_name: '精英酋长|西部大镖客|制霸全明星',
    },
    {
      ename: 169,
      cname: '后羿',
      title: '半神之弓',
      new_type: 0,
      hero_type: 5,
      skin_name: '半神之弓|精灵王|阿尔法小队|辉光之辰|黄金射手座',
    },
    {
      ename: 170,
      cname: '刘备',
      title: '仁德义枪',
      new_type: 0,
      hero_type: 1,
      skin_name: '仁德义枪|万事如意|纽约教父|汉昭烈帝',
    },
    {
      ename: 171,
      cname: '张飞',
      title: '禁血狂兽',
      new_type: 0,
      hero_type: 3,
      hero_type2: 6,
      skin_name: '禁血狂兽|五福同心|乱世虎臣',
    },
    {
      ename: 173,
      cname: '李元芳',
      title: '王都密探',
      new_type: 0,
      hero_type: 5,
      skin_name: '王都密探|特种部队|黑猫爱糖果|逐浪之夏',
    },
    {
      ename: 174,
      cname: '虞姬',
      title: '森之风灵',
      new_type: 0,
      hero_type: 5,
      skin_name: '森之风灵|加勒比小姐|霸王别姬|凯尔特女王',
    },
    {
      ename: 175,
      cname: '钟馗',
      title: '虚灵城判',
      new_type: 0,
      hero_type: 2,
      hero_type2: 1,
      skin_name: '虚灵城判|地府判官',
    },
    {
      ename: 177,
      cname: '成吉思汗',
      title: '苍狼末裔',
      new_type: 0,
      hero_type: 5,
      skin_name: '苍狼末裔|维京掠夺者',
    },
    {
      ename: 178,
      cname: '杨戬',
      title: '根源之目',
      new_type: 0,
      hero_type: 1,
      skin_name: '根源之目|埃及法老|永曜之星',
    },
    {
      ename: 183,
      cname: '雅典娜',
      title: '圣域余晖',
      pay_type: 10,
      new_type: 0,
      hero_type: 1,
      skin_name: '圣域余晖|战争女神|冰冠公主|神奇女侠',
    },
    {
      ename: 184,
      cname: '蔡文姬',
      title: '天籁弦音',
      new_type: 0,
      hero_type: 6,
      skin_name: '天籁弦音|蔷薇王座|舞动绿茵|奇迹圣诞',
    },
    {
      ename: 186,
      cname: '太乙真人',
      title: '炼金大师',
      new_type: 0,
      hero_type: 6,
      hero_type2: 3,
      skin_name: '炼金大师|圆桌骑士|饕餮|华丽摇滚',
    },
    {
      ename: 180,
      cname: '哪吒',
      title: '桀骜炎枪',
      new_type: 0,
      hero_type: 1,
      skin_name: '桀骜炎枪|三太子|逐梦之翼',
    },
    {
      ename: 190,
      cname: '诸葛亮',
      title: '绝代智谋',
      new_type: 0,
      hero_type: 2,
      skin_name: '绝代智谋|星航指挥官|黄金分割率|武陵仙君|掌控之力',
    },
    {
      ename: 192,
      cname: '黄忠',
      title: '燃魂重炮',
      new_type: 0,
      hero_type: 5,
      skin_name: '燃魂重炮|芝加哥教父',
    },
    {
      ename: 191,
      cname: '大乔',
      title: '沧海之曜',
      new_type: 0,
      hero_type: 6,
      skin_name: '沧海之曜|伊势巫女|守护之力|猫狗日记',
    },
    {
      ename: 187,
      cname: '东皇太一',
      title: '噬灭日蚀',
      new_type: 0,
      hero_type: 3,
      skin_name: '噬灭日蚀|东海龙王|逐梦之光',
    },
    {
      ename: 182,
      cname: '干将莫邪',
      title: '淬命双剑',
      new_type: 0,
      hero_type: 2,
      skin_name: '淬命双剑|第七人偶|冰霜恋舞曲',
    },
    {
      ename: 189,
      cname: '鬼谷子',
      title: '万物有灵',
      pay_type: 10,
      new_type: 0,
      hero_type: 6,
      skin_name: '万物有灵|阿摩司公爵|幻乐之宴',
    },
    {
      ename: 193,
      cname: '铠',
      title: '破灭刃锋',
      new_type: 0,
      hero_type: 1,
      hero_type2: 3,
      skin_name: '破灭刃锋|龙域领主|曙光守护者|青龙志',
    },
    {
      ename: 196,
      cname: '百里守约',
      title: '静谧之眼',
      new_type: 0,
      hero_type: 5,
      hero_type2: 4,
      skin_name: '静谧之眼|绝影神枪|特工魅影|朱雀志',
    },
    {
      ename: 195,
      cname: '百里玄策',
      title: '嚣狂之镰',
      new_type: 0,
      hero_type: 4,
      skin_name: '嚣狂之镰|威尼斯狂欢|白虎志',
    },
    {
      ename: 194,
      cname: '苏烈',
      title: '不屈铁壁',
      new_type: 0,
      hero_type: 3,
      hero_type2: 1,
      skin_name: '不屈铁壁|爱与和平|坚韧之力|玄武志',
    },
    {
      ename: 198,
      cname: '梦奇',
      title: '入梦之灵',
      new_type: 0,
      hero_type: 3,
      skin_name: '入梦之灵|美梦成真|胖达荣荣',
    },
    {
      ename: 179,
      cname: '女娲',
      title: '至高创世',
      new_type: 0,
      hero_type: 2,
      skin_name: '至高创世|尼罗河女神',
    },
    {
      ename: 501,
      cname: '明世隐',
      title: '灵魂劫卜',
      new_type: 0,
      hero_type: 6,
      skin_name: '灵魂劫卜|占星术士|虹云星官',
    },
    {
      ename: 199,
      cname: '公孙离',
      title: '幻舞玲珑',
      new_type: 0,
      hero_type: 5,
      skin_name: '幻舞玲珑|花间舞|蜜橘之夏',
    },
    {
      ename: 176,
      cname: '杨玉环',
      title: '霓裳风华',
      new_type: 0,
      hero_type: 2,
      hero_type2: 6,
      skin_name: '风华霓裳|霓裳曲|遇见飞天',
    },
    {
      ename: 502,
      cname: '裴擒虎',
      title: '六合虎拳',
      new_type: 0,
      hero_type: 4,
      hero_type2: 1,
      skin_name: '六合虎拳|街头霸王|梅西',
    },
    {
      ename: 197,
      cname: '弈星',
      title: '天元之弈',
      new_type: 0,
      hero_type: 2,
      skin_name: '天元之弈|踏雪寻梅',
    },
    {
      ename: 503,
      cname: '狂铁',
      title: '战车意志',
      new_type: 0,
      hero_type: 1,
      skin_name: '战车意志|命运角斗场|御狮',
    },
    {
      ename: 504,
      cname: '米莱狄',
      title: '筑城者',
      new_type: 0,
      hero_type: 2,
      skin_name: '筑城者|精准探案法|御霄',
    },
    {
      ename: 125,
      cname: '元歌',
      title: '无间傀儡',
      new_type: 0,
      hero_type: 4,
      skin_name: '无间傀儡|午夜歌剧院',
    },
    {
      ename: 510,
      cname: '孙策',
      title: '光明之海',
      new_type: 0,
      hero_type: 3,
      hero_type2: 1,
      skin_name: '光明之海|海之征途|猫狗日记',
    },
    {
      ename: 137,
      cname: '司马懿',
      title: '寂灭之心',
      new_type: 0,
      hero_type: 4,
      hero_type2: 2,
      skin_name: '寂灭之心|魇语军师',
    },
    {
      ename: 509,
      cname: '盾山',
      title: '无尽之盾',
      new_type: 0,
      hero_type: 6,
      skin_name: '无尽之盾|极冰防御线',
    },
    {
      ename: 508,
      cname: '伽罗',
      title: '破魔之箭',
      new_type: 0,
      hero_type: 5,
      skin_name: '破魔之箭|花见巫女',
    },
    {
      ename: 312,
      cname: '沈梦溪',
      title: '爆弹怪猫',
      new_type: 0,
      hero_type: 2,
      skin_name: '爆弹怪猫|棒球奇才',
    },
    {
      ename: 507,
      cname: '李信',
      title: '谋世之战',
      new_type: 0,
      hero_type: 1,
      skin_name: '谋世之战|灼热之刃',
    },
    {
      ename: 513,
      cname: '上官婉儿',
      title: '惊鸿之笔',
      new_type: 0,
      hero_type: 2,
      hero_type2: 4,
      skin_name: '惊鸿之笔|修竹墨客',
    },
    {
      ename: 515,
      cname: '嫦娥',
      title: '寒月公主',
      new_type: 0,
      hero_type: 2,
      hero_type2: 3,
      skin_name: '寒月公主|露花倒影',
    },
    {
      ename: 511,
      cname: '猪八戒',
      title: '无忧猛士',
      new_type: 0,
      hero_type: 3,
      skin_name: '无忧猛士|年年有余',
    },
    {
      ename: 529,
      cname: '盘古',
      title: '破晓之神',
      new_type: 0,
      hero_type: 1,
      skin_name: '破晓之神',
    },
    {
      ename: 505,
      cname: '瑶',
      title: '鹿灵守心',
      new_type: 0,
      hero_type: 6,
      skin_name: '森',
    },
    {
      ename: 506,
      cname: '云中君',
      title: '流云之翼',
      new_type: 0,
      hero_type: 4,
      hero_type2: 1,
      skin_name: '荷鲁斯之眼',
    },
    {
      ename: 522,
      cname: '曜',
      title: '星辰之子',
      new_type: 0,
      hero_type: 1,
      skin_name: '归虚梦演',
    },
    {
      ename: 518,
      cname: '马超',
      title: '冷晖之枪',
      new_type: 0,
      hero_type: 1,
      hero_type2: 4,
    },
    {
      ename: 523,
      cname: '西施',
      title: '幻纱之灵',
      new_type: 0,
      hero_type: 2,
      skin_name: '幻纱之灵|归虚梦演',
    },
    {
      ename: 525,
      cname: '鲁班大师',
      title: '神匠',
      new_type: 0,
      hero_type: 6,
      skin_name: '神匠|归虚梦演',
    },
    {
      ename: 524,
      cname: '蒙犽',
      title: '烈炮小子',
      pay_type: 10,
      new_type: 0,
      hero_type: 5,
      skin_name: '烈炮小子|归虚梦演',
    },
    {
      ename: 531,
      cname: '镜',
      title: '破镜之刃',
      new_type: 0,
      hero_type: 4,
      skin_name: '破镜之刃|冰刃幻境',
    },
    {
      ename: 527,
      cname: '蒙恬',
      title: '秩序统将',
      new_type: 1,
      hero_type: 1,
      skin_name: '秩序统将|秩序猎龙将',
    },
  ];
}

export function getToolList() {
  // return request(toolList);
  return [
    {
      item_id: 1111,
      item_name: '铁剑',
      item_type: 1,
      price: 150,
      total_price: 250,
      des1: '<p>+20物理攻击</p>',
    },
    {
      item_id: 1112,
      item_name: '匕首',
      item_type: 1,
      price: 174,
      total_price: 290,
      des1: '<p>+10%攻击速度 </p>',
    },
    {
      item_id: 1113,
      item_name: '搏击拳套',
      item_type: 1,
      price: 192,
      total_price: 320,
      des1: '<p>+8%暴击率 </p>',
    },
    {
      item_id: 1114,
      item_name: '吸血之镰',
      item_type: 1,
      price: 246,
      total_price: 410,
      des1: '<p>+10物理攻击<br>+8%物理吸血</p>',
    },
    {
      item_id: 1116,
      item_name: '雷鸣刃',
      item_type: 1,
      price: 270,
      total_price: 450,
      des1: '<p>+40物理攻击</p>',
    },
    {
      item_id: 1117,
      item_name: '冲能拳套',
      item_type: 1,
      price: 330,
      total_price: 550,
      des1: '<p>+15%暴击率</p> ',
    },
    {
      item_id: 1121,
      item_name: '风暴巨剑',
      item_type: 1,
      price: 546,
      total_price: 910,
      des1: '<p>+80物理攻击</p> ',
    },
    {
      item_id: 1122,
      item_name: '日冕',
      item_type: 1,
      price: 474,
      total_price: 790,
      des1: '<p>+40物理攻击<br>+300最大生命</p> ',
      des2:
        '<p>唯一被动-残废：普通攻击有30%几率降低敌人20%移动速度，持续2秒</p>',
    },
    {
      item_id: 1123,
      item_name: '狂暴双刃',
      item_type: 1,
      price: 534,
      total_price: 890,
      des1: '<p>+15%攻击速度<br>+10%暴击率<br>+5%移速</p>',
    },
    {
      item_id: 1124,
      item_name: '陨星',
      item_type: 1,
      price: 648,
      total_price: 1080,
      des1: '<p>+45物理攻击<br>+10%冷却缩减</p>',
      des2: '<p>唯一被动-切割：+60物理穿透</p>',
    },
    {
      item_id: 1131,
      item_name: '碎星锤',
      item_type: 1,
      price: 1260,
      total_price: 2100,
      des1: '<p>+80物理攻击<br>+10%冷却缩减</p>',
      des2: '<p>唯一被动-破甲：+40%物理穿透</p>',
    },
    {
      item_id: 1126,
      item_name: '末世',
      item_type: 1,
      price: 1296,
      total_price: 2160,
      des1: '<p>+60物理攻击<br>+30%攻击速度 <br>+10%物理吸血</p>',
      des2:
        '<p>唯一被动-破败：普通攻击附带敌人当前生命值8%的物理伤害（对野怪最多：80）</p>',
    },
    {
      item_id: 1127,
      item_name: '名刀·司命',
      item_type: 1,
      price: 1056,
      total_price: 1900,
      des1: '<p>+60物理攻击<br>+5%冷却缩减</p>',
      des2:
        '<p>唯一被动-暗幕：受到致命伤害时，进入短暂无敌状态并增加30%移动速度，持续1秒（远程英雄使用时用时持续时间缩短为0.5秒）冷却时间：120秒</p>',
    },
    {
      item_id: 1128,
      item_name: '冰霜长矛',
      item_type: 1,
      price: 1188,
      total_price: 1980,
      des1: '<p>+80物理攻击<br>+600最大生命<br>+15%攻击速度</p>',
      des2:
        '<p>唯一被动-碎冰：普通攻击会减少目标30%攻击速度和移动速度，持续2秒<br>远程英雄使用时减速效果持续时间衰减为1秒</p>',
    },
    {
      item_id: 1129,
      item_name: '速击之枪',
      item_type: 1,
      price: 534,
      total_price: 890,
      des1: '<p>+25%攻击速度</p>',
      des2:
        '<p>唯一被动-精准：普通攻击伤害提升30点，远程英雄使用时该效果翻倍。</p>',
    },
    {
      item_id: 11210,
      item_name: '制裁之刃',
      item_type: 1,
      price: 1080,
      total_price: 1800,
      des1: '<p>+100物理攻击<br>+10%物理吸血</p>',
      des2:
        '<p>唯一被动-重伤：造成伤害使得目标的生命恢复效果减少50%，持续1.5秒（如果该伤害由普攻触发，则持续时间延长至3秒）</p>',
    },
    {
      item_id: 1132,
      item_name: '泣血之刃',
      item_type: 1,
      price: 1044,
      total_price: 1740,
      des1: '<p>+100物理攻击<br>+25%物理吸血 </p>',
    },
    {
      item_id: 1133,
      item_name: '无尽战刃',
      item_type: 1,
      price: 1284,
      total_price: 2140,
      des1: '<p>+130物理攻击<br>+20%暴击率</p>',
      des2: '<p>唯一被动：+40%暴击效果</p>',
    },
    {
      item_id: 1134,
      item_name: '宗师之力',
      item_type: 1,
      price: 1260,
      total_price: 2100,
      des1: '<p>+60物理攻击<br>+20%暴击率<br>+400 最大法力<br>+400最大生命</p>',
      des2:
        '<p>唯一被动-强击：使用技能后，2秒内提升自身12%移动速度，并使得下次普通攻击造成额外0.8*物理攻击的物理伤害，冷却时间：2秒</p>',
    },
    {
      item_id: 1135,
      item_name: '闪电匕首',
      item_type: 1,
      price: 1104,
      total_price: 1840,
      des1: '<p>+35%攻击速度<br>+15%暴击率<br>+8%移速</p>',
      des2:
        '<p>唯一被动-电弧：普通攻击有30%几率释放连锁闪电，对目标造成（100+0.3*物理攻击）点法术伤害，这个伤害可以暴击，冷却时间：0.5秒</p>',
    },
    {
      item_id: 1136,
      item_name: '影刃',
      item_type: 1,
      price: 1242,
      total_price: 2070,
      des1: '<p>+40%攻击速度<br>+20%暴击率<br>+5%移速</p>',
      des2:
        '<p>唯一被动-暴风：暴击后提升自身30%攻击速度和10%移动速度，持续2秒</p>',
    },
    {
      item_id: 1137,
      item_name: '暗影战斧',
      item_type: 1,
      price: 1254,
      total_price: 2090,
      des1: '<p>+85物理攻击<br>+15%冷却缩减<br>+500最大生命</p>',
      des2:
        '<p>唯一被动-切割：增加(50+英雄等级*8)点护甲穿透<br>唯一被动-残废：普通攻击有30%几率降低敌人20%移动速度，持续2秒</p>',
    },
    {
      item_id: 1138,
      item_name: '破军',
      item_type: 1,
      price: 1770,
      total_price: 2950,
      des1: '<p>+180物理攻击 </p>',
      des2: '<p>唯一被动-破军：对生命值低于50%的敌人造成额外30%的伤害</p>',
    },
    {
      item_id: 11311,
      item_name: '纯净苍穹',
      item_type: 1,
      price: 1338,
      total_price: 2230,
      des1: '<p>+40%攻击速度<br>+20%暴击率</p>',
      des2:
        '<p>唯一被动-精准：普通攻击伤害提升35点，远程英雄使用时该效果翻倍。<br>唯一主动-驱散：90秒CD，受到的所有伤害降低50%，持续1.5秒，可以在被控制时使用。</p>',
    },
    {
      item_id: 91040,
      item_name: '逐日之弓',
      item_type: 1,
      price: 1260,
      total_price: 2100,
      des1: '<p>+25%攻击速度<br>+15%暴击</p>',
      des2:
        '<p>唯一被动-精准：普通攻击伤害提升35点，远程英雄使用时该效果翻倍。<br>唯一主动-逐日：增加自己150点普攻射程和40%移动速度，持续5秒，冷却时间：60秒（增加射程效果仅远程英雄生效）</p>',
    },
    {
      item_id: 1125,
      item_name: '破魔刀',
      item_type: 1,
      price: 1200,
      total_price: 2000,
      des1: '<p>+100物理攻击<br>+150法术防御</p>',
      des2:
        '<p>唯一被动-破魔：获得额外的法术防御，数值等于你的物理攻击*0.5且最多增加300点</p>',
    },
    {
      item_id: 1154,
      item_name: '穿云弓',
      item_type: 1,
      price: 660,
      total_price: 1100,
      des1: '<p>+40物理攻击<br>+10%攻击速度</p>',
      des2: '<p>唯一被动-破甲：+10%物理穿透（远程英雄使用时效果翻倍）</p>',
    },
    {
      item_id: 1155,
      item_name: '破晓',
      item_type: 1,
      price: 2040,
      total_price: 3400,
      des1: '<p>+50物理攻击<br>+35%攻击速度<br>+10%暴击率</p>',
      des2:
        '<p>唯一被动-破甲：+20%物理穿透（远程英雄使用时效果翻倍）<br>唯一被动：普通攻击伤害提升50点（远程英雄使用时效果翻倍）</p>',
    },
    {
      item_id: 1211,
      item_name: '咒术典籍',
      item_type: 2,
      price: 180,
      total_price: 300,
      des1: '<p>+40法术攻击</p> ',
    },
    {
      item_id: 1212,
      item_name: '蓝宝石',
      item_type: 2,
      price: 132,
      total_price: 220,
      des1: '<p>+300最大法力</p>',
    },
    {
      item_id: 1213,
      item_name: '炼金护符',
      item_type: 2,
      price: 72,
      total_price: 120,
      des1: '<p>+10 每5秒回蓝</p> ',
    },
    {
      item_id: 1214,
      item_name: '圣者法典',
      item_type: 2,
      price: 300,
      total_price: 500,
      des1: '<p>+20法术攻击<br>+8%冷却缩减</p> ',
    },
    {
      item_id: 1216,
      item_name: '元素杖',
      item_type: 2,
      price: 324,
      total_price: 540,
      des1: '<p>+80法术攻击</p> ',
    },
    {
      item_id: 1221,
      item_name: '大棒',
      item_type: 2,
      price: 492,
      total_price: 820,
      des1: '<p>+120法术攻击</p>',
    },
    {
      item_id: 1229,
      item_name: '破碎圣杯',
      item_type: 2,
      price: 480,
      total_price: 800,
      des1: '<p>+80法术攻击<br>+5%冷却缩减<br>+20 每5秒回蓝</p>',
    },
    {
      item_id: 1223,
      item_name: '光辉之剑',
      item_type: 2,
      price: 438,
      total_price: 730,
      des1: '<p>+400最大生命<br>+400最大法力</p> ',
      des2:
        '<p>唯一被动-强击：使用技能后，5秒内的下一次普通攻击附加50%物理攻击（+30%法术加成）的法术伤害，这个效果有2秒的冷却时间</p>',
    },
    {
      item_id: 1224,
      item_name: '魅影面罩',
      item_type: 2,
      price: 612,
      total_price: 1020,
      des1: '<p>+70法术攻击<br>+300最大生命</p>',
      des2:
        '<p>唯一被动-折磨：技能命中敌人时，会对目标造成(125+英雄等级*5)点法术伤害，冷却时间：2秒</p>',
    },
    {
      item_id: 1225,
      item_name: '进化水晶',
      item_type: 2,
      price: 432,
      total_price: 720,
      des1: '<p>+400最大法力<br>+400最大生命</p>',
      des2: '<p>唯一被动-英勇奖赏：升级后在3秒内回复20%生命与法力值</p>',
    },
    {
      item_id: 1222,
      item_name: '血族之书',
      item_type: 2,
      price: 744,
      total_price: 1240,
      des1: '<p>+75法术攻击<br>+10%冷却缩减</p>',
      des2: '<p>唯一被动-嗜血：增加20%法术吸血</p>',
    },
    {
      item_id: 1227,
      item_name: '炽热支配者',
      item_type: 2,
      price: 1170,
      total_price: 1950,
      des1: '<p>+180法术攻击<br>+600最大法力<br>+15 每5秒回蓝</p>',
      des2:
        '<p>唯一被动-法力护盾：血量低于30%时立即解除自身控制，同时获得一个吸收（500+1.5*法术攻击）伤害的护盾，护盾持续期间提升30%移动速度，持续4秒，冷却时间：90秒</p>',
    },
    {
      item_id: 12211,
      item_name: '梦魇之牙',
      item_type: 2,
      price: 1230,
      total_price: 2050,
      des1: '<p>+240法术攻击<br>+5%移速</p>',
      des2:
        '<p>唯一被动-重伤：造成伤害使得目标的生命恢复效果减少50%，持续1.5秒（如果该伤害由普攻触发，则持续时间延长至3秒）</p>',
    },
    {
      item_id: 1231,
      item_name: '虚无法杖',
      item_type: 2,
      price: 1266,
      total_price: 2110,
      des1: '<p>+240法术攻击<br>+300最大生命值</p>',
      des2: '<p>唯一被动：+45%法术穿透</p>',
    },
    {
      item_id: 1232,
      item_name: '博学者之怒',
      item_type: 2,
      price: 1380,
      total_price: 2300,
      des1: '<p>+240法术攻击</p>',
      des2: '<p>唯一被动-毁灭：法术攻击提升35%</p>',
    },
    {
      item_id: 1239,
      item_name: '辉月',
      item_type: 2,
      price: 1194,
      total_price: 1990,
      des1: '<p>+160法术攻击<br>+10%冷却缩减</p>',
      des2:
        '<p>唯一主动-月之守护：90秒CD，免疫所有效果，不能移动、攻击和使用技能，持续1.5秒</p>',
    },
    {
      item_id: 1233,
      item_name: '回响之杖',
      item_type: 2,
      price: 1260,
      total_price: 2100,
      des1: '<p>+240法术攻击 <br>+7%移速 </p>',
      des2:
        '<p>唯一被动-回响：技能命中会触发小范围爆炸造成100（+40%法术加成）法术伤害，这个效果有5秒CD</p>',
    },
    {
      item_id: 1234,
      item_name: '冰霜法杖',
      item_type: 2,
      price: 1260,
      total_price: 2100,
      des1: '<p>+180法术攻击 <br>+1200最大生命</p>',
      des2:
        '<p>唯一被动-结霜：英雄技能造成伤害会附带20%的减速效果，持续2秒</p>',
    },
    {
      item_id: 1235,
      item_name: '痛苦面具',
      item_type: 2,
      price: 1224,
      total_price: 2040,
      des1: '<p>+120法术攻击<br>+5%冷却缩减<br>+800最大生命</p>',
      des2:
        '<p>唯一被动-折磨：技能命中敌人时会每0.5秒造成当前生命值3%的法术伤害，持续2秒，对野怪每次最多造成200点伤害，冷却时间：2秒',
    },
    {
      item_id: 1236,
      item_name: '巫术法杖',
      item_type: 2,
      price: 1272,
      total_price: 2120,
      des1: '<p>+140法术攻击<br>+400最大生命<br>+400最大法力<br>+8%移速</p>',
      des2:
        '<p>唯一被动-强击：使用技能后，5秒内下一次普通攻击附加30%物理攻击（+80%法术加成）的法术伤害，这个效果有3秒冷却时间</p>',
    },
    {
      item_id: 1226,
      item_name: '圣杯',
      item_type: 2,
      price: 1080,
      total_price: 1800,
      des1: '<p>+180法术攻击<br>+15%冷却缩减<br>+25每5秒回蓝</p>',
      des2:
        '<p>唯一被动-法力源泉：每秒回复1%法力值，如果法力值已满，每秒回复1%生命值</p>',
    },
    {
      item_id: 1237,
      item_name: '时之预言',
      item_type: 2,
      price: 1254,
      total_price: 2090,
      des1: '<p>+140法术攻击<br>+500最大法力<br>+800最大生命</p>',
      des2:
        '<p>唯一被动-英勇奖赏：升级后在3秒内回复20%生命值与法力值<br>唯一被动-守护： 获得额外的物理和法术防御，数值等于你的法术攻击*0.4，且最多不超过250点。</p>',
    },
    {
      item_id: 1238,
      item_name: '贤者之书',
      item_type: 2,
      price: 1794,
      total_price: 2990,
      des1: '<p>+400法术攻击</p>',
      des2: '<p>唯一被动-刻印：增加1600点生命</p>',
    },
    {
      item_id: 1240,
      item_name: '噬神之书',
      item_type: 2,
      price: 1254,
      total_price: 2090,
      des1: '<p>+180法术攻击<br>+10%冷却缩减<br>+800最大生命</p>',
      des2: '<p>唯一被动-嗜血：增加25%法术吸血</p>',
    },
    {
      item_id: 1311,
      item_name: '红玛瑙',
      item_type: 3,
      price: 180,
      total_price: 300,
      des1: '<p>+300最大生命</p>',
    },
    {
      item_id: 1312,
      item_name: '布甲',
      item_type: 3,
      price: 132,
      total_price: 220,
      des1: '<p>+90物理防御</p>',
    },
    {
      item_id: 1313,
      item_name: '抗魔披风',
      item_type: 3,
      price: 132,
      total_price: 220,
      des1: '<p>+90法术防御</p>',
    },
    {
      item_id: 1314,
      item_name: '提神水晶',
      item_type: 3,
      price: 84,
      total_price: 140,
      des1: '<p>+30 每5秒回复</p>',
    },
    {
      item_id: 1321,
      item_name: '力量腰带',
      item_type: 3,
      price: 540,
      total_price: 900,
      des1: '<p>+1000最大生命</p>',
    },
    {
      item_id: 1322,
      item_name: '熔炼之心',
      item_type: 3,
      price: 540,
      total_price: 900,
      des1: '<p>+700最大生命</p>',
      des2:
        '<p>唯一被动-献祭：每秒对身边300范围内的敌人造成（60+英雄等级*2）点法术伤害</p>',
    },
    {
      item_id: 1323,
      item_name: '神隐斗篷',
      item_type: 3,
      price: 612,
      total_price: 1020,
      des1: '<p>+120法术防御<br>+700最大生命<br>+50每5秒回血</p>',
    },
    {
      item_id: 1324,
      item_name: '雪山圆盾',
      item_type: 3,
      price: 540,
      total_price: 900,
      des1: '<p>+10%减CD<br>+400最大法力<br>+110物理防御</p>',
    },
    {
      item_id: 1325,
      item_name: '守护者之铠',
      item_type: 3,
      price: 438,
      total_price: 730,
      des1: '<p>+210物理防御</p>',
      des2: '<p>唯一被动-寒铁：受到攻击会减少攻击者15%攻击速度，持续3秒</p>',
    },
    {
      item_id: 1724,
      item_name: '近卫荣耀',
      item_type: 7,
      price: 1206,
      total_price: 2010,
      des1: '<p>+10%移动速度<br>+1000最大生命</p>',
      des2:
        '<p>唯一被动-解放：拔除其他装备中的奉献效果，周围小兵和野怪死亡后你可以与队友平分收益。<br>唯一被动-守护光环：提升周围800范围友军(54+英雄等级*6）点物理防御和法术防御<br>多个辅助装光环无法同时生效<br>唯一被动-恩赐：如果自己的经验或经济是己方最低，每3秒会额外获得5点经验或金币。</p>',
    },
    {
      item_id: 1723,
      item_name: '奔狼纹章',
      item_type: 7,
      price: 1254,
      total_price: 2090,
      des1: '<p>+10%移动速度<br>+1000最大生命</p>',
      des2:
        '<p>唯一被动-解放：拔除其他装备中的奉献效果，周围小兵和野怪死亡后你可以与队友平分收益。<br>唯一被动-恩赐：如果自己的经验或经济是己方最低，每3秒会额外获得5点经验或金币。<br>唯一主动-奔腾号令：给自己和周围友军增加移速，3秒内会递增35%+15%*英雄等级的移速，一共持续5秒，受到英雄攻击或敌方英雄攻击则效果消失，冷却时间：120秒。所有同CD辅助装备的主动技能均为全队共享冷却时间</p>',
    },
    {
      item_id: 1327,
      item_name: '反伤刺甲',
      item_type: 3,
      price: 1104,
      total_price: 1840,
      des1: '<p>+40物理攻击<br>+420物理防御</p>',
      des2:
        '<p>唯一被动-荆棘：受到物理伤害时，会将伤害量的20%以法术伤害的形式回敬给对方。自身每20点物理防御属性提升1%该伤害（最多+100%）。攻击者距离越远，这个伤害越低，最多在距离800时衰减至70%</p>',
    },
    {
      item_id: 1328,
      item_name: '血魔之怒',
      item_type: 3,
      price: 1272,
      total_price: 2120,
      des1: '<p>+20物理攻击<br>+1000最大生命</p>',
      des2:
        '<p>唯一主动-血怒：逐渐扣除30%当前生命值，逐渐获得40%最大生命值的护盾，并增加80点物理攻击，持续4秒。<br>冷却时间：60秒</p>',
    },
    {
      item_id: 1331,
      item_name: '红莲斗篷',
      item_type: 3,
      price: 1098,
      total_price: 1830,
      des1: '<p>+240物理防御<br>+1000最大生命</p>',
      des2:
        '<p>唯一被动-献祭：每秒对身边300范围内的敌人造成使用者最大生命值2%的法术伤害</p>',
    },
    {
      item_id: 1332,
      item_name: '霸者重装',
      item_type: 3,
      price: 1242,
      total_price: 2070,
      des1: '<p>+2000最大生命<br>+100每5秒回血</p>',
      des2: '<p>唯一被动-复苏：脱离战斗后每秒回复3%最大生命值</p>',
    },
    {
      item_id: 1341,
      item_name: '冲击铠甲',
      item_type: 3,
      price: 1260,
      total_price: 2100,
      des1: '<p>+240物理防御<br>+800最大生命</p>',
      des2:
        '<p>唯一主动-冲击：使用后1.5秒对500范围内敌人造成50%减速1秒，内圈敌人还会额外造成眩晕0.5秒（改动前，内圈眩晕，外圈减速；改动后，内圈眩晕+减速，外圈只有减速）<br> 冷却时间：90秒</p>',
    },
    {
      item_id: 1333,
      item_name: '不祥征兆',
      item_type: 3,
      price: 1308,
      total_price: 2180,
      des1: '<p>+270物理防御<br>+1200最大生命</p>',
      des2:
        '<p>唯一被动-寒铁：受到攻击会减少攻击者30%攻击速度与15%移动速度，持续3秒</p>',
    },
    {
      item_id: 1334,
      item_name: '不死鸟之眼',
      item_type: 3,
      price: 1260,
      total_price: 2100,
      des1: '<p>+100每5秒回血<br>+240法术防御<br>+1200最大生命</p>',
      des2:
        '<p>唯一被动-血统：每损失10%生命值，受到的所有治疗效果会额外增加6%。</p>',
    },
    {
      item_id: 1335,
      item_name: '魔女斗篷',
      item_type: 3,
      price: 1272,
      total_price: 2120,
      des1: '<p>+360法术防御<br>+1000最大生命</p>',
      des2:
        '<p>唯一被动-迷雾：脱战3秒后获得一个吸收（200+英雄等级*120）点法术伤害的护盾</p>',
    },
    {
      item_id: 1336,
      item_name: '极寒风暴',
      item_type: 3,
      price: 1260,
      total_price: 2100,
      des1: '<p>+20%冷却缩减<br>+500最大法力<br>+360物理防御</p>',
      des2:
        '<p>唯一被动-冰心：受到单次伤害超过当前生命值10%时触发寒冰冲击，对周围敌人造成（50+英雄等级*10）点法术伤害并降低其30%攻击和移动速度，持续2秒，这个效果有2秒内置CD</p>',
    },
    {
      item_id: 13310,
      item_name: '冰痕之握',
      item_type: 3,
      price: 1212,
      total_price: 2020,
      des1:
        '<p>+800最大生命<br>+500最大法力<br>+10%冷却缩减<br>+240物理防御</p>',
      des2:
        '<p>唯一被动-强击：使用技能后，5秒内的下一次普攻造成范围30%减速（远程英雄使用时减速效果衰减为20%）与（150+英雄等级*20）点物理伤害，这个效果有3秒的冷却时间</p>',
    },
    {
      item_id: 1337,
      item_name: '贤者的庇护',
      item_type: 3,
      price: 1248,
      total_price: 2080,
      des1: '<p>+140物理防御<br>+140法术防御</p>',
      des2:
        '<p>唯一被动-复生：死亡后2秒原地复活，并获得（2000+英雄等级*100）点生命值，冷却时间：150秒。这个效果每局游戏只能触发2次</p>',
    },
    {
      item_id: 1338,
      item_name: '暴烈之甲',
      item_type: 3,
      price: 1170,
      total_price: 1950,
      des1: '<p>+220物理防御<br>+1000最大生命</p>',
      des2:
        '<p>唯一被动-无畏：每次受到伤害后，自身造成的所有伤害提升2%并增加2%的移速，这个效果最高可以叠加5层，最多提升10%的伤害输出和10%移速，持续3秒</p>',
    },
    {
      item_id: 1411,
      item_name: '神速之靴',
      item_type: 4,
      price: 150,
      total_price: 250,
      des1: '<p>唯一被动：+30移动速度</p>',
      des2: '<p>所有鞋类装备的移速加成效果不叠加</p>',
    },
    {
      item_id: 1421,
      item_name: '影忍之足',
      item_type: 4,
      price: 426,
      total_price: 710,
      des1: '<p>+110物理防御</p>',
      des2:
        '<p>唯一被动：+60移动速度（所有鞋类装备的移速加成效果不叠加）<br>唯一被动：减少15%受到普通攻击的伤害</p>',
    },
    {
      item_id: 1422,
      item_name: '抵抗之靴',
      item_type: 4,
      price: 426,
      total_price: 710,
      des1: '<p>+110法术防御</p>',
      des2:
        '<p>唯一被动：+60移动速度（所有鞋类装备的移速加成效果不叠加）<br>唯一被动：+35%韧性</p>',
    },
    {
      item_id: 1423,
      item_name: '冷静之靴',
      item_type: 4,
      price: 426,
      total_price: 710,
      des1: '<p>+15%减CD</p>',
      des2:
        '<p>唯一被动-静谧：所有英雄技能的冷却恢复速度加快3%~10%（随英雄等级成长）这个效果对剩余冷却时间小于5秒的技能不会生效。<br>唯一被动：+60移动速度（所有鞋类装备的移速加成效果不叠加）</p>',
    },
    {
      item_id: 1424,
      item_name: '秘法之靴',
      item_type: 4,
      price: 426,
      total_price: 710,
      des1: '<p>+25 每5秒回蓝</p>',
      des2:
        '<p>唯一被动：+60移动速度（所有鞋类装备的移速加成效果不叠加）<br>唯一被动-法术精通：获得(45+英雄等级*5)点法术穿透</p>',
    },
    {
      item_id: 1425,
      item_name: '急速战靴',
      item_type: 4,
      price: 426,
      total_price: 710,
      des1: '<p>+25%攻速</p>',
      des2: '<p>唯一被动：+60移动速度（所有鞋类装备的移速加成效果不叠加）</p>',
    },
    {
      item_id: 1426,
      item_name: '疾步之靴',
      item_type: 4,
      price: 318,
      total_price: 530,
      des1:
        '<p>唯一被动-神行：脱离战斗后增加60移动速度<br>唯一被动：+60移动速度（所有鞋类装备的移速加成效果不叠加）</p>',
    },
    {
      item_id: 1511,
      item_name: '狩猎宽刃',
      item_type: 5,
      price: 150,
      total_price: 250,
      des1:
        '<p>（打野刀升级后将惩戒技能替换为寒冰惩戒：寒冰惩戒可对英雄使用，造成伤害和减速效果）<br>必须携带惩击才可够买</p>',
      des2:
        '<p>唯一被动-打野：增加50%对野怪的伤害（仅近战英雄生效），自己击杀或500范围内友方击杀野怪时，自己会额外获得20%经验</p>',
    },
    {
      item_id: 1521,
      item_name: '游击弯刀',
      item_type: 5,
      price: 450,
      total_price: 750,
      des1: '<p>必须携带惩击才可够买，获得寒冰惩击效果</p>',
      des2:
        '<p>唯一被动-打野：增加60%对野怪的伤害（仅近战英雄生效），自己击杀或500范围内友方击杀野怪时，自己会额外获得30%经验和20%金币<br>唯一被动-磨砺：自己击杀或500范围内友方击杀野怪增加自身6点法术攻击，最多叠加20层</p>',
    },
    {
      item_id: 1522,
      item_name: '巡守利斧',
      item_type: 5,
      price: 450,
      total_price: 750,
      des1:
        '<p>唯一被动-献祭：每秒对范围内的野怪和小兵造成自身2%最大生命值的法术伤害（对英雄不生效）<br>必须携带惩击才可够买，获得寒冰惩击效果</p>',
      des2:
        '<p>唯一被动-打野：增加60%对野怪的伤害（仅近战英雄生效），自己击杀或500范围内友方击杀野怪时，自己会额外获得30%经验和20%金币<br>唯一被动-磨砺：自己击杀或500范围内友方击杀野怪增加自身50点最大生命，最多叠加10层</p>',
    },
    {
      item_id: 1523,
      item_name: '追击刀锋',
      item_type: 5,
      price: 450,
      total_price: 750,
      des1: '<p>必须携带惩击才可够买，获得寒冰惩击效果</p>',
      des2:
        '<p>唯一被动-打野：增加60%对野怪的伤害（仅近战英雄生效），自己击杀或500范围内友方击杀野怪时，自己会额外获得30%经验和20%金币<br>唯一被动-磨砺：自己击杀或500范围内友方击杀野怪增加自身2点物理攻击和0.5%冷却缩减，最多叠加20层</p>',
    },
    {
      item_id: 1531,
      item_name: '符文大剑',
      item_type: 5,
      price: 1296,
      total_price: 2160,
      des1:
        '<p>+100法术攻击<br>+400最大法力<br>必须携带惩击才可够买，获得寒冰惩击效果</p>',
      des2:
        '<p>唯一被动-强击：使用技能后，5秒内的下一次普通攻击附加50+0.5*法术攻击的法术伤害，冷却时间：2秒<br>唯一被动-打野：增加60%对野怪的伤害（仅近战英雄生效），自己击杀或500范围内友方击杀野怪时，自己会额外获得30%经验和20%金币<br>唯一被动-磨砺：自己击杀或500范围内友方击杀野怪增加自身6点法术攻击，最多叠加30层</p>',
    },
    {
      item_id: 1532,
      item_name: '巨人之握',
      item_type: 5,
      price: 1080,
      total_price: 1800,
      des1:
        '<p>+120物理防御<br>+120法术防御<br>必须携带惩击才可够买，获得寒冰惩击效果</p>',
      des2:
        '<p>唯一被动-献祭：每秒对身边小范围的敌人造成自身2%最大生命值的法术伤害<br>唯一被动-打野：增加60%对野怪的伤害（仅近战英雄生效），自己击杀或500范围内友方击杀野怪时，自己会额外获得30%经验和20%金币<br>唯一被动-磨砺：自己击杀或500范围内友方击杀野怪增加自身50点最大生命，最多叠加15层</p>',
    },
    {
      item_id: 1533,
      item_name: '贪婪之噬',
      item_type: 5,
      price: 1296,
      total_price: 2160,
      des1:
        '<p>+40物理攻击<br>+20%攻击速度<br>+8%移速<br>必须携带惩击才可够买，获得寒冰惩击效果</p>',
      des2:
        '<p>唯一被动-打野：增加60%对野怪的伤害（仅近战英雄生效），自己击杀或500范围内友方击杀野怪时，自己会额外获得30%经验和20%金币<br>唯一被动-磨砺：自己击杀或500范围内友方击杀野怪增加自身2点物理攻击和0.5%冷却缩减，最多叠加30层</p>',
    },
    {
      item_id: 1714,
      item_name: '鼓舞之盾',
      item_type: 7,
      price: 726,
      total_price: 1210,
      des1: '<p>+5%移动速度<br>+500最大生命</p>',
      des2:
        '<p>唯一被动-奉献：己方所有出了辅助装的英雄中如果自己经济最低，当身边有队友时，周围小兵和野怪死亡后你的队友会获得全额收益，你会获得不影响队友的30%金币和经验。<br>唯一被动-守护光环：提升周围800范围友军(36+英雄等级*4）点物理防御和法术防御<br>多个辅助装光环无法同时生效<br>唯一被动-恩赐：如果自己的经验或经济是己方最低，每3秒会额外获得5点经验或金币。</p>',
    },
    {
      item_id: 1713,
      item_name: '风灵纹章',
      item_type: 7,
      price: 708,
      total_price: 1180,
      des1: '<p>+5%移动速度<br>+500最大生命</p>',
      des2:
        '<p>唯一被动-奉献：己方所有出了辅助装的英雄中如果自己经济最低，当身边有队友时，周围小兵和野怪死亡后你的队友会获得全额收益，你会获得不影响队友的30%金币和经验。<br>唯一被动-恩赐：如果自己的经验或经济是己方最低，每3秒会额外获得5点经验或金币。<br>唯一主动-奔腾号令：给自己和周围友军增加移速，3秒内会递增21%+9%*英雄等级的移速，一共持续5秒，受到英雄攻击或对敌方英雄攻击则消失，冷却时间：120秒。<br>所有同CD辅助装的主动技能均为全队共享冷却时间</p>',
    },
    {
      item_id: 1722,
      item_name: '救赎之翼',
      item_type: 7,
      price: 1080,
      total_price: 1800,
      des1: '<p>+10%移动速度<br>+1000最大生命</p>',
      des2:
        '<p>唯一被动-解放：拔除其他装备中的奉献效果，周围小兵和野怪死亡后你可以与队友平分收益。<br>唯一被动-恩赐：如果自己的经验或经济是己方最低，每3秒会额外获得5点经验或金币<br>唯一主动-救援：立即为周围友方英雄（包括自己）提供一个吸收（ 600+60*英雄等级）伤害的护盾，持续3秒，冷却时间：60秒。所有同CD辅助装备的主动技能均为全队共享冷却时间</p>',
    },
    {
      item_id: 1712,
      item_name: '风之轻语',
      item_type: 7,
      price: 606,
      total_price: 1010,
      des1: '<p>+5%移速<br>+500最大生命</p>',
      des2:
        '<p>唯一被动-奉献：己方所有出了辅助装的英雄中如果自己经济最低，当身边有队友时，周围小兵和野怪死亡后你的队友会获得全额收益，你会获得不影响队友的30%金币和经验。<br>唯一被动-恩赐：如果自己的经验或经济是己方最低，每3秒会额外获得5点经验或金币。<br>唯一主动-救援：立即为周围友方英雄（包括自己）提供一个吸收（380+38*英雄等级）伤害的护盾，持续3秒，冷却时间：60秒。所有同CD辅助装的主动技能均为全队共享冷却时间</p>',
    },
    {
      item_id: 1721,
      item_name: '极影',
      item_type: 7,
      price: 1146,
      total_price: 1910,
      des1: '<p>+10%移动速度<br>+1000最大生命</p>',
      des2:
        '<p>唯一被动-解放：拔除其他装备中的奉献效果，周围小兵和野怪死亡后你可以与队友平分收益。<br>唯一被动-迅捷光环：提升周围800范围友军30%攻击速度和10%冷却缩减。<br>多个辅助装光环无法同时生效<br>唯一被动-恩赐：如果自己的经验或经济是己方最低，每3秒会额外获得5点经验或金币。</p>',
    },
    {
      item_id: 1725,
      item_name: '星泉',
      item_type: 7,
      price: 1128,
      total_price: 1880,
      des1: '<p>+1000最大生命<br>+10%移动速度</p>',
      des2:
        '<p>唯一被动-解放：拔除其他装备中的奉献效果，周围小兵和野怪死亡后你可以与队友平分收益。<br>唯一被动-恩赐：如果自己的经验或经济是己方最低，每3秒会额外获得5点经验或金币。<br>唯一主动-星芒：立即与周围血量最低的友方英雄建立链接，分摊其50%所受伤害。链接在超过一定范围后会断开，持续2秒，冷却时间：60秒。所有同CD辅助装备的主动技能均为全队共享冷却时间</p>',
    },
    {
      item_id: 1726,
      item_name: '星之佩饰',
      item_type: 7,
      price: 600,
      total_price: 1000,
      des1: '<p>+500最大生命<br>+5%移动速度</p>',
      des2:
        '<p>唯一被动-奉献：己方所有出了辅助装的英雄中如果自己经济最低，当身边有队友时，周围小兵和野怪死亡后你的队友会获得全额收益，你会获得不影响队友的30%金币和经验。<br>唯一被动-恩赐：如果自己的经验或经济是己方最低，每3秒会额外获得5点经验或金币。<br>唯一主动-星芒：立即与周围血量最低的友方英雄建立链接，分摊其50%所受伤害。链接在超过一定范围后会断开，持续2秒，冷却时间：60秒。所有同CD辅助装备的主动技能均为全队共享冷却时间</p>',
    },
    {
      item_id: 1711,
      item_name: '凤鸣指环',
      item_type: 7,
      price: 642,
      total_price: 1070,
      des1: '<p>+5%移动速度<br>+500最大生命</p>',
      des2:
        '<p>唯一被动-奉献：己方所有出了辅助装的英雄中如果自己经济最低，当身边有队友时，周围小兵和野怪死亡后你的队友会获得全额收益，你会获得不影响队友的30%金币和经验。<br>唯一被动-迅捷光环：提升周围800范围友军20%攻击速度和6%冷却缩减。<br>多个辅助装光环无法同时生效<br>唯一被动-恩赐：如果自己的经验或经济是己方最低，每3秒会额外获得5点经验或金币。</p>',
    },
    {
      item_id: 1701,
      item_name: '学识宝石',
      item_type: 7,
      price: 180,
      total_price: 300,
      des1: '<p>+5%移动速度</p>',
      des2:
        '<p>唯一被动-奉献：己方所有出了辅助装的英雄中如果自己经济最低，当身边有队友时，周围小兵和野怪死亡后你的队友会获得全额收益，你会获得不影响队友的30%金币和经验。<br>唯一被动-恩赐：如果自己的经验或经济是己方最低，每3秒会额外获得5点经验或金币。</p>',
    },
    {
      item_id: 1727,
      item_name: '日暮之流',
      item_type: 2,
      price: 1272,
      total_price: 2120,
      des1: '<p>+180法术攻击<br>+10%冷却缩减</p>',
      des2:
        '<p>唯一被动-日暮时分：对英雄造成伤害会获得(9+英雄等级*1)点法术穿透，持续4秒，该效果可叠加10层。</p>',
    },
    {
      item_id: 1728,
      item_name: '金色圣剑',
      item_type: 2,
      price: 1242,
      total_price: 2070,
      des1: '<p>+140法术攻击<br>+20%攻击速度<br>+5%移动速度</p>',
      des2:
        '<p>唯一被动-圣剑：普攻命中敌人会获得10%攻速，持续5秒，最多可叠加两层；叠满后，普攻会额外附带(0.3*法术攻击)点法术伤害，该伤害冷却时间：0.2秒。<br>唯一被动-精准：普通攻击伤害提升35点，远程英雄使用时该效果翻倍。</p>',
    },
  ];
}

export function getSkillList() {
  // return request(skillList);
  return [
    {
      summoner_id: 80104,
      summoner_name: '惩击',
      summoner_rank: 'LV.1解锁',
      summoner_description: '30秒CD：对身边的野怪和小兵造成真实伤害并眩晕1秒',
    },
    {
      summoner_id: 80108,
      summoner_name: '终结',
      summoner_rank: 'LV.3解锁',
      summoner_description:
        '90秒CD：立即对身边敌军英雄造成其已损失生命值14%的真实伤害',
    },
    {
      summoner_id: 80110,
      summoner_name: '狂暴',
      summoner_rank: 'LV.5解锁',
      summoner_description:
        '60秒CD：使用期间增加10%伤害、增加15%韧性、20%的物理吸血和法术吸血，持续7秒',
    },
    {
      summoner_id: 80109,
      summoner_name: '疾跑',
      summoner_rank: 'LV.7解锁',
      summoner_description:
        '100秒CD：增加30%移动速度持续10秒，且使用期间不受减速效果的影响',
    },
    {
      summoner_id: 80102,
      summoner_name: '治疗术',
      summoner_rank: 'LV.9解锁',
      summoner_description:
        '120秒CD：回复自己与附近队友15%生命值，提高附近友军移动速度15%持续2秒',
    },
    {
      summoner_id: 80105,
      summoner_name: '干扰',
      summoner_rank: 'LV.11解锁',
      summoner_description:
        '60秒CD：对敌方机关使用，沉默机关持续6秒；对己方机关使用，使己方机关免疫所有伤害4秒，同时攻击速度提升100%；60秒内叠加效果只有1秒的有效时间',
    },
    {
      summoner_id: 80103,
      summoner_name: '晕眩',
      summoner_rank: 'LV.13解锁',
      summoner_description:
        '90秒CD：晕眩身边所有敌人0.75秒，并附带持续1秒的减速效果',
    },
    {
      summoner_id: 80107,
      summoner_name: '净化',
      summoner_rank: 'LV.15解锁',
      summoner_description:
        '120秒CD：解除自身所有负面和控制效果并免疫控制持续1.5秒',
    },
    {
      summoner_id: 80121,
      summoner_name: '弱化',
      summoner_rank: 'LV.17解锁',
      summoner_description:
        '90秒CD：减少身边敌人伤害输出25%，并增加自身20%的免伤率，持续4秒',
    },
    {
      summoner_id: 80115,
      summoner_name: '闪现',
      summoner_rank: 'LV.19解锁',
      summoner_description: '120秒CD：向指定方向位移一段距离',
    },
  ];
}
